import Head from "next/head";
import {useDispatch,useSelector} from 'react-redux'
import { fetchAllUser } from "../redux/action";
import styles from "../styles/Home.module.css";
import { wrapper } from "../redux/store";

export const getServerSideProps = wrapper.getServerSideProps(async ({store}) => {
  const dispatch = store.dispatch  
  await dispatch(await fetchAllUser());
});

 const Home = () => {

  const Users = useSelector(state => state.userReducer.users)

  return (
    <div className={styles.container}>
      <Head>
        <title>Next redux crud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
{
  Users.map(data=>(
    <p key={data.id}>{data.name}</p>
  ))
}
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Simple Next-redux crud
        </a>
      </footer>
    </div>
  );
}

export default Home

